"""Generate the tmux lockdown block appended to terminal_tmux.conf.

Verified identical between tmux 3.4 and 3.5a (Debian trixie ships 3.5a): the
only default-binding change between those releases is M-6/M-7 in the prefix
table, which this file removes anyway.
"""

# Copy-mode keys that survive the wipe, with tmux's own default commands.
# `\;` (not a bare `;`) is required: tmux treats an unescaped semicolon as a
# command separator and would truncate the binding to its first command.
KEEP = [
    ("WheelUpPane",       r"select-pane \; send-keys -X -N 5 scroll-up"),
    ("WheelDownPane",     r"select-pane \; send-keys -X -N 5 scroll-down"),
    ("Up",                "send-keys -X cursor-up"),
    ("Down",              "send-keys -X cursor-down"),
    ("PPage",             "send-keys -X page-up"),
    ("NPage",             "send-keys -X page-down"),
    ("MouseDown1Pane",    "select-pane"),
    ("MouseDrag1Pane",    r"select-pane \; send-keys -X begin-selection"),
    ("MouseDragEnd1Pane", "send-keys -X copy-pipe-and-cancel"),
    ("DoubleClick1Pane",  r"select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe-and-cancel"),
    ("TripleClick1Pane",  r"select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-pipe-and-cancel"),
    ("Escape",            "send-keys -X cancel"),
]
TABLES = ["copy-mode", "copy-mode-vi"]
# The only root-table bindings worth keeping, verbatim from tmux's own
# defaults (key-bindings.c, identical in 3.4 and 3.5a). Everything else tmux
# ships there -- middle-click paste, border resize, the four status-bar routes,
# both pane menus and their Alt variants -- is dropped by omission.
ROOT_KEEP = [
    ("MouseDown1Pane",   "{ select-pane -t=; send -M }"),
    ("WheelUpPane",      "{ if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' { send -M } { copy-mode -e } }"),
    ("MouseDrag1Pane",   "{ if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' { send -M } { copy-mode -M } }"),
    ("DoubleClick1Pane", "{ select-pane -t=; if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' { send -M } { copy-mode -H; send -X select-word; run -d0.3; send -X copy-pipe-and-cancel } }"),
    ("TripleClick1Pane", "{ select-pane -t=; if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' { send -M } { copy-mode -H; send -X select-line; run -d0.3; send -X copy-pipe-and-cancel } }"),
]

def q(c):
    return '"' + c.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("#", "\\#") + '"'

def key(c):
    # tmux splits on a bare ';' even inside quotes, so that key alone is
    # written backslash-escaped and unquoted.
    return r"\;" if c == ";" else q(c)

out = []
w = out.append
w("# ============================================================================")
w("# Workspace terminals behave as a plain terminal: scroll and type, nothing")
w("# else. Generated by gen_lockdown.py -- edit that, not this.")
w("# ============================================================================")
w("")
w("# --- 1. No tmux features from the keyboard ----------------------------------")
w("# No prefix key at all, so every Ctrl-b command is gone: copy-mode via `[`,")
w("# clock-mode, choose-tree/client/buffer, customize-mode, new window, splits,")
w("# detach, suspend-client, the command prompt. Ctrl-b instead reaches the shell")
w("# as readline's backward-char.")
w("set -g prefix  None")
w("set -g prefix2 None")
w("unbind -a -T prefix")
w("")
w("# Uncomment to also hide the status bar. sigwinch_panes.sh already maps")
w("# `status off` to 0 rows, so pane height stays correct either way.")
w("# set -g status off")
w("")
w("# --- 2. The mouse stays on, so scrollback still works ------------------------")
w("# Deliberately NOT `set -g mouse off` or `unbind -a -T root`: either kills")
w("# wheel scrolling and drag-to-copy. Per tmux's maintainer, copy-mode is the")
w("# only scrollback viewer there is -- github.com/tmux/tmux/issues/2550 -- so")
w("# wheel-up entering copy-mode is not avoidable. Section 5 makes it harmless.")
w("set -g mouse on")
w("")
w("# Not a key binding, so no unbind reaches it: if this were ever set, the")
w("# session would lock on idle and demand a password. Pin it off.")
w("set -g lock-after-time 0")
w("")
w("# --- 3. The root table (no-prefix keys), also a whitelist -------------------")
w("# tmux ships 16 root bindings. Wipe them and put back only the five mouse")
w("# routes a plain terminal needs. Dropped by omission: middle-click paste,")
w("# border drag-resize, the four status-bar tab routes (click / wheel / right-")
w("# click menus), and both pane context menus -- the pane menu in particular")
w("# swallows every keystroke until dismissed.")
w("unbind -a -T root")
for k, cmd in ROOT_KEEP:
    w(f"bind -n {k:<18} {cmd}")
w("")
w("# mngr's Ctrl-q (destroy agent) and Ctrl-t (stop agent) are left alone on")
w("# purpose -- that is mngr behaviour, not tmux's.")
w("")
w("# --- 5. Copy-mode, rebuilt as a whitelist -----------------------------------")
w("# tmux ships 72 copy-mode and 87 copy-mode-vi bindings. Listing the unwanted")
w("# ones is a blacklist: it misses whatever tmux adds next, and it silently")
w("# misses every control and meta key -- C-s opens \"(search down)\", C-r")
w("# \"(search up)\", M-1..M-9 a \"(repeat)\" count prompt. So both tables are wiped")
w("# and only what a scroll-and-read view needs goes back. Precedence:")
w("#   a. the navigation / mouse keys below -- scroll, select, copy")
w("#   b. every printable character -- leaves the mode AND types itself")
w("#   c. Any -- the catch-all: every other key just leaves the mode")
w("# Per tmux(1), \"a command bound to the Any key will execute for all keys which")
w("# do not have a more specific binding\", so a and b win over c, and anything")
w("# tmux adds upstream lands in c instead of eating input. b needs one binding")
w("# per character because no format exposes the key that triggered a binding.")
for t in TABLES:
    w(f"unbind -a -T {t}")
w("")
w("# a. navigation, selection and the OSC 52 copy path (verbatim tmux defaults)")
for t in TABLES:
    for k, cmd in KEEP:
        w(f"bind -T {t:<12} {k:<18} {cmd}")
    w("")
w("# b. every printable character leaves copy-mode and is typed into the shell")
for i in range(0x20, 0x7F):
    c = chr(i)
    for t in TABLES:
        w(f"bind -T {t:<12} {key(c):<6} {{ send -X cancel ; send-keys -l {q(c)} }}")
w("")
w("# c. catch-all: control, meta, function -- anything else just leaves the mode")
for t in TABLES:
    w(f"bind -T {t:<12} Any    send -X cancel")
print("\n".join(out))
