import { describe, expect, it } from "vitest";
import { isHiddenUserMessage } from "./message-classification";

describe("isHiddenUserMessage", () => {
  it("folds only skill-expansion messages out of the inline stream", () => {
    // The SKILL.md body Claude Code injects is shown in its "Tool: Skill" block
    // instead of as a multi-hundred-line inline chip; it is the one thing not
    // rendered inline.
    expect(isHiddenUserMessage("Base directory for this skill: /x/skills/caretaker/SKILL.md")).toBe(true);
  });

  it("shows everything else -- the chat reflects the full raw stream", () => {
    // Seed/trigger commands and Claude Code's local-command caveat all render.
    expect(isHiddenUserMessage("/welcome")).toBe(false);
    expect(isHiddenUserMessage("/caretaker")).toBe(false);
    expect(isHiddenUserMessage("  /caretaker  \n")).toBe(false);
    expect(isHiddenUserMessage("/clear")).toBe(false);
    expect(isHiddenUserMessage("/caretaker-welcome")).toBe(false);
    expect(
      isHiddenUserMessage(
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond",
      ),
    ).toBe(false);
    expect(isHiddenUserMessage("can you run /caretaker for me?")).toBe(false);
    expect(isHiddenUserMessage("hello there")).toBe(false);
  });
});
