import { describe, expect, it } from "vitest";
import { isHiddenUserMessage } from "./message-classification";

describe("isHiddenUserMessage", () => {
  it("hides the main chat's /welcome seed command so the first visible turn is the greeting", () => {
    // The desktop client seeds the main chat with "/welcome"; the user should see
    // the assistant's greeting, not the trigger.
    expect(isHiddenUserMessage("/welcome")).toBe(true);
  });

  it("tolerates surrounding whitespace on the seed command", () => {
    expect(isHiddenUserMessage("  /welcome  \n")).toBe(true);
  });

  it("shows the Caretaker's /caretaker and /clear commands (not hidden)", () => {
    // These reflect what actually happened on each run, so the chat shows them
    // rather than hiding the commands behind the scenes.
    expect(isHiddenUserMessage("/caretaker")).toBe(false);
    expect(isHiddenUserMessage("  /caretaker  \n")).toBe(false);
    expect(isHiddenUserMessage("/clear")).toBe(false);
  });

  it("does not hide the retired /caretaker-welcome command", () => {
    // /caretaker-welcome no longer exists -- the idempotent /caretaker skill handles
    // the welcome itself -- so it is treated as an ordinary message, not a seed.
    expect(isHiddenUserMessage("/caretaker-welcome")).toBe(false);
  });

  it("hides the local-command caveat that follows a /clear", () => {
    // Claude Code injects an agent-directed caveat after a local command like
    // /clear; it is noise for the user, so it stays hidden even though /clear shows.
    expect(
      isHiddenUserMessage(
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond",
      ),
    ).toBe(true);
  });

  it("hides skill-expansion messages", () => {
    expect(isHiddenUserMessage("Base directory for this skill: /x/skills/caretaker/SKILL.md")).toBe(true);
  });

  it("does not hide a genuine user prompt that merely mentions a command", () => {
    expect(isHiddenUserMessage("can you run /caretaker for me?")).toBe(false);
    expect(isHiddenUserMessage("hello there")).toBe(false);
  });
});
